### ISSUE TITLE
Upload small documents take too long

### ISSUE THREAD

**Issue by oizidbih** [El-Technology/Ellogy_App_Backend#20]
![Screen Shot 2024-02-15 at 12 24 45](https://github.com/El-Technology/Ellogy_App_Backend/assets/65413532/cf1585de-38df-4d5a-ad97-af733d55ad9e)

![Screen Shot 2024-02-15 at 12 27 23](https://github.com/El-Technology/Ellogy_App_Backend/assets/65413532/51be96cb-2784-4491-9db2-7409280d51d5)

![Screen Shot 2024-02-15 at 12 39 02](https://github.com/El-Technology/Ellogy_App_Backend/assets/65413532/3cd5d657-2e59-4c8c-b05f-ce8e2beba768)

**Comment by Sharkovskyi** [comment]
> ![Screen Shot 2024-02-15 at 12 24 45](https://private-user-images.githubusercontent.com/65413532/305019805-cf1585de-38df-4d5a-ad97-af733d55ad9e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTA3OTcsIm5iZiI6MTcwNzk5MDQ5NywicGF0aCI6Ii82NTQxMzUzMi8zMDUwMTk4MDUtY2YxNTg1ZGUtMzhkZi00ZDVhLWFkOTctYWY3MzNkNTVhZDllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA5NDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0Yzk2YmJlNTdjNjIxOTA0ZWJlMDc2YTZjMTY0MzBlYTM0NjRhMDEyY2U4MTRmMzUyZDJkOTQyNDhlOGNhY2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RUAwIKKhnhv-8MZAFjUHkm1gcW2LjRztx7a7sotHUJ0)
> 
> ![Screen Shot 2024-02-15 at 12 27 23](https://private-user-images.githubusercontent.com/65413532/305023592-51be96cb-2784-4491-9db2-7409280d51d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTA3OTcsIm5iZiI6MTcwNzk5MDQ5NywicGF0aCI6Ii82NTQxMzUzMi8zMDUwMjM1OTItNTFiZTk2Y2ItMjc4NC00NDkxLTlkYjItNzQwOTI4MGQ1MWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA5NDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZjJhZDY3MTM5ZTIxMmJmMzk3MDQ5MzYwNTMxZjMzYzQ4NmRmMmU0ODIxNTRjNWIwZjY2NDg2ZGMwNzc2MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NMlnCyV1Z9lEB8xRxu9C08UAEEIQ1xuCYnOLHgZYnJk)
> 
> ![Screen Shot 2024-02-15 at 12 39 02](https://private-user-images.githubusercontent.com/65413532/305023656-3cd5d657-2e59-4c8c-b05f-ce8e2beba768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5OTA3OTcsIm5iZiI6MTcwNzk5MDQ5NywicGF0aCI6Ii82NTQxMzUzMi8zMDUwMjM2NTYtM2NkNWQ2NTctMmU1OS00YzhjLWIwNWYtY2U4ZTJiZWJhNzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE1VDA5NDgxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMDc3OTAxYTc3MWQ4YWU4M2NkNjk1YjRjYTY4YWNiZTY3ZDYyMTZkOGE0Njc2NTFmMjhlNmQyM2IwODk3Y2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.96YhN7Gg-eTZ09dUOt1P-Dbs3YkHnlTnt0_THRWuQjg)

Hello, upload documents logic was reconfigured for adding sharing functionality, it`s works properly, but for now, the front-end part on the dev server is not deployed with changes, so you are not able to do tests. We apologize for the inconvenience, please give us some time and we will let you know when we can start testing
