### ISSUE TITLE
The login is blocked due to unsecure connection

### ISSUE THREAD

**Issue by oizidbih** [El-Technology/Ellogy_App_Backend#21]
The login is blocked due to unsecure connection

<img width="952" alt="Screenshot 2024-02-18 092128" src="https://github.com/El-Technology/Ellogy_App_Backend/assets/65413532/a06a7ce2-4e2a-468e-90e8-d276c11a6d52">

**Comment by Sharkovskyi** [comment]
> The login is blocked due to unsecure connection
> 
> <img alt="Screenshot 2024-02-18 092128" width="952" src="https://private-user-images.githubusercontent.com/65413532/305689175-a06a7ce2-4e2a-468e-90e8-d276c11a6d52.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMjkxNDAsIm5iZiI6MTcwODMyODg0MCwicGF0aCI6Ii82NTQxMzUzMi8zMDU2ODkxNzUtYTA2YTdjZTItNGUyYS00NjhlLTkwZTgtZDI3NmMxMWE2ZDUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDA3NDcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzNDFiMzllZDgwM2FiYmQzMDZlNGRhMDdmYmRhYmM5MmFmZDhjZDc4N2I4NGYyZTQ0ZDRmNzA0OGU0ZGFmNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vc-Tg-n_vpDpV7EVIcbiZ7b4XH-BEI6pjyCcXO4XESQ">

Hi, the error is strange, as the CORS policy should be configured for all pages with the domain "ellogy.ai", I tried to reproduce the error - failed, the server logs were also clean, no errors, however I added additional settings in the cloud for this anyway. If the situation happens again, please send a screenshot from the "network" tab to a specific request to the server part that failed. Until I close the ticket, thank you for the message!

*I have attached an example of a screenshot
![network sample](https://github.com/El-Technology/Ellogy_App_Backend/assets/140795985/6de10bf3-e6b5-4822-ac74-cbd02d85548d)

**Comment by oizidbih** [comment]
This is network view
![Screenshot 2024-02-25 095043](https://github.com/El-Technology/Ellogy_App_Backend/assets/65413532/d904eace-f60b-4a55-8dd3-b39cbf6a5b2d)
