### ISSUE TITLE
backend not connected on prod

### ISSUE THREAD

**Issue by oizidbih** [El-Technology/Ellogy_App_Backend#22]
<img width="1676" alt="Screen Shot 2024-03-23 at 16 16 25" src="https://github.com/El-Technology/Ellogy_App_Backend/assets/65413532/683a31ae-9bf6-42b7-a478-2e87db5ce0a3">

**Comment by Sharkovskyi** [comment]
Need to test more

**Comment by Sharkovskyi** [comment]
If 

> <img alt="Screen Shot 2024-03-23 at 16 16 25" width="1676" src="https://private-user-images.githubusercontent.com/65413532/316243374-683a31ae-9bf6-42b7-a478-2e87db5ce0a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNTM4NTEsIm5iZiI6MTcxMTM1MzU1MSwicGF0aCI6Ii82NTQxMzUzMi8zMTYyNDMzNzQtNjgzYTMxYWUtOWJmNi00MmI3LWE0NzgtMmU4N2RiNWNlMGEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDA3NTkxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkYjdmN2FmOTlmOTAzZjhiMDljNDYzZWYyMjI3OWVjMTIzZDYyYWYxYmNmMzk3YmEzZDE2NTFkZWVkMGQ1ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x68DscJmYc1W_kyGJP7-XT8BN5ZB61Z7umLdaDwWLJU">

If you are talking about a 400 error when receiving a plantUml image, then this is an expected error from our side, it means that the image was generated incorrectly and cannot be extracted.

I don't see any other notifications about the backend side, if I'm wrong please clarify, otherwise close the issue
